name: Daily Analysis

on:
  push:
    branches:
      - main # Assuming you want to run this on the main branch. Adjust as necessary.
  schedule:
    - cron: '0 */3 * * *' # This will run the action every 3 hours
    - cron: '0 0 * * *' # This will run the action every day at midnight (you can keep this if you want the daily run as well)

jobs:
  analysis:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openai pandas matplotlib

    - name: Run analysis
      run: python main.py
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    
    - name: Commit and push results
      run: |
        DATE_STR=$(date +"%Y%m%d%H")
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add results_dir/dataframe-$DATE_STR.csv results_dir/plot-$DATE_STR.jpg
        git commit -m "Automated analysis results update - $(date +"%D %T")"
        git push